"""crear_esquema_inicial

Revision ID: 6fc0b3050d3e
Revises: 
Create Date: 2026-08-21 09:59:53.327436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc0b3050d3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_rut'), 'pacientes', ['rut'], unique=True)
    op.create_table('derivaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('especialidad', sa.String(length=255), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='Pendiente', nullable=False),
    sa.Column('responsable', sa.String(length=255), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('Pendiente', 'En revisión', 'Agendada', 'Atendida', 'Cerrada', 'Cancelada')", name='ck_derivaciones_estado_valido'),
    sa.CheckConstraint("prioridad IN ('Alta', 'Media', 'Baja')", name='ck_derivaciones_prioridad_valida'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_derivaciones_paciente_id'), 'derivaciones', ['paciente_id'], unique=False)
    op.create_table('historial_derivaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('derivacion_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['derivacion_id'], ['derivaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_derivaciones_derivacion_id'), 'historial_derivaciones', ['derivacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_derivaciones_derivacion_id'), table_name='historial_derivaciones')
    op.drop_table('historial_derivaciones')
    op.drop_index(op.f('ix_derivaciones_paciente_id'), table_name='derivaciones')
    op.drop_table('derivaciones')
    op.drop_index(op.f('ix_pacientes_rut'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
